// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(FamilyBudgetDbContext))]
    [Migration("20231112203650_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("expense_category_hilo")
                .IncrementsBy(10);

            modelBuilder.HasSequence("expense_hilo")
                .IncrementsBy(10);

            modelBuilder.HasSequence("income_category_hilo")
                .IncrementsBy(10);

            modelBuilder.HasSequence("income_hilo")
                .IncrementsBy(10);

            modelBuilder.HasSequence("shared_expense_hilo")
                .IncrementsBy(10);

            modelBuilder.Entity("DataAccess.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "expense_hilo");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExpenseCategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Expense", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 50.0m,
                            Description = "Grocery shopping",
                            ExpenseCategoryId = 1,
                            ExpenseDate = new DateTime(2023, 11, 12, 21, 36, 50, 778, DateTimeKind.Local).AddTicks(6059),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 30.0m,
                            Description = "Fuel",
                            ExpenseCategoryId = 2,
                            ExpenseDate = new DateTime(2023, 11, 12, 21, 36, 50, 778, DateTimeKind.Local).AddTicks(6080),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 30.0m,
                            Description = "Fuel",
                            ExpenseCategoryId = 2,
                            ExpenseDate = new DateTime(2023, 11, 12, 21, 36, 50, 778, DateTimeKind.Local).AddTicks(6082),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("DataAccess.Models.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "expense_category_hilo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExpenseCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fuel"
                        });
                });

            modelBuilder.Entity("DataAccess.Models.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "income_hilo");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IncomeCategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncomeCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Income", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5000.0m,
                            Date = new DateTime(2023, 11, 12, 21, 36, 50, 778, DateTimeKind.Local).AddTicks(6106),
                            Description = "Salary",
                            IncomeCategoryId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("DataAccess.Models.IncomeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "income_category_hilo");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IncomeCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Salary"
                        });
                });

            modelBuilder.Entity("DataAccess.Models.SharedExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "shared_expense_hilo");

                    b.Property<int>("ExpenseId")
                        .HasColumnType("int");

                    b.Property<decimal>("SharedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SharingUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId");

                    b.HasIndex("SharingUserId");

                    b.ToTable("SharedExpense", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpenseId = 1,
                            SharedAmount = 0m,
                            SharingUserId = 2
                        });
                });

            modelBuilder.Entity("DataAccess.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            UserName = "Adam990"
                        },
                        new
                        {
                            UserId = 2,
                            UserName = "Janusz889"
                        });
                });

            modelBuilder.Entity("DataAccess.Models.Expense", b =>
                {
                    b.HasOne("DataAccess.Models.ExpenseCategory", "ExpenseCategory")
                        .WithMany()
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Models.User", "User")
                        .WithMany("UserExpenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccess.Models.Income", b =>
                {
                    b.HasOne("DataAccess.Models.IncomeCategory", "IncomeCategory")
                        .WithMany()
                        .HasForeignKey("IncomeCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Models.User", "User")
                        .WithMany("Incomes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccess.Models.SharedExpense", b =>
                {
                    b.HasOne("DataAccess.Models.Expense", "Expense")
                        .WithMany("SharedWith")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Models.User", "SharingUser")
                        .WithMany("SharedExpenses")
                        .HasForeignKey("SharingUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Expense");

                    b.Navigation("SharingUser");
                });

            modelBuilder.Entity("DataAccess.Models.Expense", b =>
                {
                    b.Navigation("SharedWith");
                });

            modelBuilder.Entity("DataAccess.Models.User", b =>
                {
                    b.Navigation("Incomes");

                    b.Navigation("SharedExpenses");

                    b.Navigation("UserExpenses");
                });
#pragma warning restore 612, 618
        }
    }
}
